### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by mikrokode** [MicroPyramid/Django-CRM#123]
Hi,

I have just downloaded your app and try to run. 
When i run it with the python manage.py runserver command?
I have installed the PostgreSQL.
The following error appear when I browser the link. http://127.0.0.1:8000/

**C:\Users\kiantat.wong\Desktop\Django-CRM\Django-CRM-master>python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
October 14, 2018 - 12:55:39
Django version 2.1.2, using settings 'crm.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[14/Oct/2018 12:55:46] "GET / HTTP/1.1" 302 0
[14/Oct/2018 12:55:47] "GET /login/?next=/ HTTP/1.1" 500 1293**

![500 error](https://user-images.githubusercontent.com/26881536/46912762-231c0500-cfb1-11e8-8d44-10c2fa5d660b.jpg)

May I know what is the the problem and how to solve it?

**Comment by dahjah** [comment]
I'm getting this same error. I'm not sure where it's coming from yet

**Comment by Donny42** [comment]
change DEBUG to True and it will work

**Comment by officerebel** [comment]
I get this error TemplateDoesNotExist at /login/
login.html 

Request Method: | GET
-- | --
http://localhost:8000/login/?next=/
2.1.2
TemplateDoesNotExist
login.html

**Comment by guili618** [comment]
Please go to the crm folder，and  change the ‘DEBUG’ value to ‘True’ in settings.py, then runserver to see the error,I guess probably is '/bin/sh: 1: sass: not found' ,you should install sass !!!

**Comment by nikhila05** [comment]
@officerebel @dahjah  @mikrokode 

Please follow the instructions in README.md file to install system requirements.

You need to install SASS for compiling scss files.

**Comment by lugezz** [comment]
It is not in readme file, either on the requirements.txt. Thanks for your comments.

**Comment by rkisdp** [comment]
nothing is given in readme or requirements.txt file. Please help us solving issue.
