### ISSUE TITLE
Email and Planner apps disabled in urls.py

### ISSUE THREAD

**Issue by smacktrace** [MicroPyramid/Django-CRM#14]
You have the email and planner apps commented out in the main crm/urls.py.  Is this intentional as you are still developing this CRM?  Are you planning to add documentation on how to enable these features at http://django-crm.readthedocs.io ? These features/documentation would be very helpful!

    # url(r'^emails/', include('emails.urls', namespace='emails')),
    # url(r'^planner/', include('planner.urls', namespace='planner')),

**Comment by btenaglia** [comment]
Hello, What is the reason for emails and planners are commented? Are these modules ready to use?

**Comment by jeremyklein** [comment]
I uncommented these modules and found the following:

- the email module requires an email server, and fails when trying to send an email. When I have some more time I will try setting up FakeSMTP and seeing how far that goes.

- The planner module does not seem to work as load_meetings function in the view references a "created_user" and "updated user" field while the model has a "created_by" and "updated_by" field

I can try to get these modules working, but I'm kind of shooting in the dark as to what the functionality is supposed to do. Is there any sort of test plan or set of requirements for these features?

**Comment by jeremyklein** [comment]
I changed the backend to the Django Dummy backend. This seemed to fix the only issue I found with the email module. There was also a link to an inbox, but I saw no code to implement this feature. I removed the Inbox link from each of the pages. If anyone has some requirements around how the Inbox should would I would be happy to try to implement. 

 I submitted a pull request with my updates.

**Comment by ashwin31** [comment]
@smacktrace we planned to develop and release those at a later stage. We will start those and other enhancements as you are interested.

**Comment by ashwin31** [comment]
#16 merged.
