### ISSUE TITLE
In accounts,contacts,leads modules of their create pages for phone number field it's placeholder should be changed 

### ISSUE THREAD

**Issue by snehamp** [MicroPyramid/Django-CRM#155]

**Comment by jeromecc** [comment]
Hi!
I am testing the app now on https://django-crm.micropyramid.com
Various countries and businesses have very different ways of writing phone numbers. I think your validation methods are not practical. For instance i would enter a French phone number either like this 0601020304 or like this +33601020304 for international use or on mobile (whatsapp compatible).

I am not sure validation is warranted at all, or, if it is, it should defined by the users.

Nice work! Thanks.
jérôme
