### ISSUE TITLE
How can we import a few thousand uses to this model?

### ISSUE THREAD

**Issue by datatalking** [MicroPyramid/Django-CRM#191]
**Describe the bug**

**To Reproduce**

**Expected behavior**
We were hoping to use the django crm as a python based crm tool and we can't add them one by one. There are django modules that have a csv or tsv import method, can one be added here?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ashwin31** [comment]
@datatalking we don't have options to create users by uploading csv file. I can develop that if that's what you want exactly.
