### ISSUE TITLE
Create tasks

### ISSUE THREAD

**Issue by sanaani** [MicroPyramid/Django-CRM#211]
Create tasks with functionality similar to that of Salesforce. Tasks should be assignable to Contact, Company, Case, Opportunity, etc.

The software in its current state is unusable to me as a salesperson without the ability to assign tasks, due dates, etc.

**Comment by vineeshan** [comment]
@sanaani Right now we don't have tasks functionality. But you can create opportunities, cases etc. and assign to users, you can set deadline too.

We are going to implement more features in Django CRM in our next release and we welcome your inputs to implement these kind of features.

**Comment by vineeshan** [comment]
@sanaani We have updated the Tasks module into live. You can check it now.
