### ISSUE TITLE
First account has to be created from admin

### ISSUE THREAD

**Issue by sanaani** [MicroPyramid/Django-CRM#222]
Steps to recreate from a blank project:

1. Create a Contact
2. Visit /accounts/create/

It shows a warning message about needing to create a contact, even though a contact already exists. None of the form fields show.

Once I added the first Account from /admin, the form appeared on /accounts/create/

**Comment by sanaani** [comment]
The problem is that an Account can only be created if both a Contact and Lead exist, which is an unnecessary requirement.

**Comment by vineeshan** [comment]
@sanaani This issue has been fixed now. But atleast there should be a single contact, to create an account.
