### ISSUE TITLE
Can't create a user from admin

### ISSUE THREAD

**Issue by sanaani** [MicroPyramid/Django-CRM#224]
Steps to recreate:

- Create a user from admin
- Now try logging in from "/" with the new credentials. It doesn't work.

**Comment by vineeshan** [comment]
@sanaani This is working now. Could you please check it once.

**Comment by sanaani** [comment]
@vineeshan I don't see any new commits referencing a few on #224 from either master or new_changes. Are you sure the changes have been pushed?

**Comment by vineeshan** [comment]
@sanaani Yesterday I've checked the scenario you have specified. But it's working fine for me. I'm not getting any issues. So, could you please check it once.
