### ISSUE TITLE
How to add  my user in CRM ? 

### ISSUE THREAD

**Issue by eleutherius** [MicroPyramid/Django-CRM#23]
Hello, I am get source Django-CRM. Start server by "python manage.py runserver", open login page to CRM , but I dont know how to add my account data in to. Can you tell me how to add account date  to the CRM?

**Comment by mahmoudhossam** [comment]
Try using [`python manage.py createsuperuser`](https://docs.djangoproject.com/en/1.11/ref/django-admin/#createsuperuser).

**Comment by vineeshan** [comment]
@eleutherius To access Django-CRM, first you need to create super user,

**Step 1:** Try `python manage.py createsuperuser` from your terminal and press enter

**Step 2:** Then below details will be prompted, 
Username:
Email:
Password:
Password (again):

**Step 3:** After giving above details, you will get a message as `Super user created successfully`

**Step 4:** Return to Django-CRM login page and login with the above credentials. You will be able to see the dashboard

**Comment by Denisolt** [comment]
i dont know why, but I dont get the users tab although i am logged in with the super user credentials
