### ISSUE TITLE
How to optimize pagination for large queryset?

### ISSUE THREAD

**Issue by juno249** [MicroPyramid/Django-CRM#230]
Hello everyone,

I got some troubles when making queryset to the table has more than 5 million records. Does anyone have a solution for this situation?

**Comment by vineeshan** [comment]
@juno249 This issue has been fixed now. If you are facing any issues with the pagination in any of your applications, please use [Django Simple Pagination](https://github.com/MicroPyramid/django-simple-pagination) to get rid of those problems
