### ISSUE TITLE
 'sass' is not recognized

### ISSUE THREAD

**Issue by mikrokode** [MicroPyramid/Django-CRM#231]
Exception Value: | 'sass' is not recognized as an internal or external command, operable program or batch file.
-- | --

May I know how to solve it ?

**Comment by vineeshan** [comment]
@mikrokode Is node.js installed on your local? If you have node.js, run the below command in terminal or windows command prompt as administrator **npm install -g sass**  If you don't have node.js installed, download and install it from this site [nodejs.org](https://nodejs.org), and then install **npm install -g sass**

**Comment by Aleccc** [comment]
Node.js...That sounds a lot like a dependency that should be included in the installation documentation.

**Comment by askolsam** [comment]
@mikrokode I've been using [SassC](https://github.com/sass/sassc) and haven't yet experienced any issues. That said, I've only been toying with Django-CRM a couple of weeks. 

SassC is available at least in Debian 9 (stretch), Fedora 30, Alpine Linux edge and in CentOS 7, if EPEL repository is enabled. I suspect it's available in many other distros too.

Just remember to modify the **COMPRESS_PRECOMPILERS** -tuple in your **settings.py** accordingly.
