### ISSUE TITLE
Transfer Lead comments to Account when converted

### ISSUE THREAD

**Issue by Aleccc** [MicroPyramid/Django-CRM#234]
Feature enhancement.
Comments attached to a Lead are not accessible after a lead is converted to an account. That seems functionally incorrect.

**Comment by Aleccc** [comment]
Lead in status Converted no longer appears in either Open or Closed tabs.

**Comment by vineeshan** [comment]
@Aleccc We are tranfering the lead comments to accounts now. You can check that in account view page.

And converted lead will be moved to accounts permanently. It won't be available in either open or closed leads.
