### ISSUE TITLE
Cannot edit Account after converting from Lead

### ISSUE THREAD

**Issue by Aleccc** [MicroPyramid/Django-CRM#235]
This may only be an issue if you start with only one open lead.

- create one contact
- create one lead
- convert lead to account
- edit Account in hopes of adding the contact
- since there are no active leads, edit Account page states to create contacts and leads to create an account

**Comment by vineeshan** [comment]
@Aleccc We have removed mandatory option for the lead field in account edit page now. So, you can edit the account now.
