### ISSUE TITLE
forget password

### ISSUE THREAD

**Issue by avigehlot05** [MicroPyramid/Django-CRM#257]
whenver i forget my password 
SMTPSenderRefused at /password-reset/
(550, b'Unauthenticated senders not allowed', 'no-reply@django-crm.micropyramid.com')

**Comment by nikhila05** [comment]
@avigehlot05 
these should be configured in settings file to fix that issue
EMAIL_HOST = <your email host> 
EMAIL_HOST_USER = <your username> EMAIL_HOST_PASSWORD = <your password>
