### ISSUE TITLE
whnver i send mail as a draft invoice error ..

### ISSUE THREAD

**Issue by avigehlot05** [MicroPyramid/Django-CRM#258]
SyntaxError at /invoices/send-mail/1/
invalid syntax (redis.py, line 22)

**Comment by avigehlot05** [comment]
![image](https://user-images.githubusercontent.com/53207348/61997514-273c8d80-b0c0-11e9-8b34-fa9f0804b1c8.png)

**Comment by avigehlot05** [comment]
this error happen on live

**Comment by vineeshan** [comment]
@avigehlot05 This issue has been fixed. You can check it now.
