### ISSUE TITLE
Login page error: Could not find an option named "scss" 

### ISSUE THREAD

**Issue by calinbule** [MicroPyramid/Django-CRM#260]
Hello,

I am trying to run the crm locally on MacOS X. I created a virtual environment, installed all dependencies, created the database and migrated the changes. I also installed sass via homebrew and the html to pdf tool via installer. According to the installation info provided it should all run smooth... but it doesn't. I can't even reach the login page. I turned on debug and the source of the error seems to be django-compressor. The error is:

```
Unable to apply CachedCompilerFilter (sass --scss {infile} {outfile})
Could not find an option named "scss"
```

I tried all possible workarounds I could find on both github and stackoverflow but they don't work.

**Comment by iColdPlayer** [comment]
@calinbule Have u tried to pull from the master itself? I've made a PR that already merged and fix the `sass` & `scss` issue. See https://github.com/MicroPyramid/Django-CRM/pull/303
