### ISSUE TITLE
create lead form is not working

### ISSUE THREAD

**Issue by admill1519** [MicroPyramid/Django-CRM#283]
I am new to django. So, this question might sound stupid to you guys but I really need help with it. Hi I am trying to add new fields in create lead form but its not working. Field I am trying to add is multichoice field same as assigned_to but its charfield not Manytomanyfield. Can somebody give me the code example of how I can add One multichoice field. You can check code on 

https://stackoverflow.com/questions/57852524/django-form-is-not-valid-but-not-giving-me-an-error#comment102133499_57852524

**Comment by nikhila05** [comment]
We'll prefer adding a many to many field instead of going for charfield.

Here is the solution for adding multichoice field for lead.

# add this in leads/templates/create_lead.html
```
<div class="filter_col col-md-12">
    <div class="form-group">
        <label for="exampleInputEmail1">Products</label>
            <select class="assigned_users form-control" name="products" multiple="multiple">
                {% for pro in product %}
                <option value="{{pro.name}}" {% if pro in lead_obj.product.all %} selected="" {% endif %}>{{pro.name}}</option>
                {% endfor %}
            </select>
        <span class="error error_message" id="error_id_products">{{ lead_form.product.errors }}</span>
    </div>
</div>

```
# add this in leads/forms.py in LeadForm class
```
# add this in leads/forms.py in LeadForm class
def clean_product(self):
    products = self.cleaned_data.get('products')
    if not Products.objects.filter(name__in=products):
        raise forms.ValidationError('select valid products')
    return products

```

**Comment by admill1519** [comment]
Can you help me with the models.py and views.py code or above code is sufficient to achieve what I required.

**Comment by nikhila05** [comment]
@admill1519 please use the above updated code, you need to send products info in **product** variable.

**Comment by admill1519** [comment]
@login_required
@sales_access_required
def create_lead(request):
    template_name = "create_lead.html"
    users = []
    if request.user.role == 'ADMIN' or request.user.is_superuser:
        users = User.objects.filter(is_active=True).order_by('email')
    elif request.user.google.all():
        users = []
    else:
        users = User.objects.filter(role='ADMIN').order_by('email')
    form = LeadForm(assigned_to=users)

    if request.POST:
        form = LeadForm(request.POST, request.FILES, assigned_to=users)
        print(request.POST)
        if form.is_valid():
            lead_obj = form.save(commit=False)
            lead_obj.created_by = request.user
            lead_obj.save()
            if request.POST.get('tags', ''):
                tags = request.POST.get("tags")
                splitted_tags = tags.split(",")
                for t in splitted_tags:
                    tag = Tags.objects.filter(name=t)
                    if tag:
                        tag = tag[0]
                    else:
                        tag = Tags.objects.create(name=t)
                    lead_obj.tags.add(tag)
            if request.POST.getlist('assigned_to', []):
                lead_obj.assigned_to.add(*request.POST.getlist('assigned_to'))
                assigned_to_list = request.POST.getlist('assigned_to')


            if request.POST.getlist('products', []):
                lead_obj.products.add(*request.POST.getlist('products'))
                products = request.POST.getlist('products')

            if request.POST.getlist('teams', []):
                user_ids = Teams.objects.filter(id__in=request.POST.getlist('teams')).values_list('users', flat=True)
                assinged_to_users_ids = lead_obj.assigned_to.all().values_list('id', flat=True)
                for user_id in user_ids:
                    if user_id not in assinged_to_users_ids:
                        lead_obj.assigned_to.add(user_id)

            current_site = get_current_site(request)
            recipients = list(lead_obj.assigned_to.all().values_list('id', flat=True))
            send_email_to_assigned_user.delay(recipients, lead_obj.id, domain=current_site.domain,
                protocol=request.scheme)

            if request.FILES.get('lead_attachment'):
                attachment = Attachments()
                attachment.created_by = request.user
                attachment.file_name = request.FILES.get(
                    'lead_attachment').name
                attachment.lead = lead_obj
                attachment.attachment = request.FILES.get('lead_attachment')
                attachment.save()

            if request.POST.get('status') == "converted":
                account_object = Account.objects.create(
                    created_by=request.user, name=lead_obj.account_name,
                    email=lead_obj.email, phone=lead_obj.phone,
                    description=request.POST.get('description'),
                    website=request.POST.get('website'),
                )
                account_object.billing_address_line = lead_obj.address_line
                account_object.billing_street = lead_obj.street
                account_object.billing_city = lead_obj.city
                account_object.billing_state = lead_obj.state
                account_object.billing_postcode = lead_obj.postcode
                account_object.billing_country = lead_obj.country
                for tag in lead_obj.tags.all():
                    account_object.tags.add(tag)

                if request.POST.getlist('assigned_to', []):
                    # account_object.assigned_to.add(*request.POST.getlist('assigned_to'))
                    assigned_to_list = request.POST.getlist('assigned_to')
                    current_site = get_current_site(request)
                    recipients = assigned_to_list
                    send_email_to_assigned_user.delay(recipients, lead_obj.id, domain=current_site.domain,
                        protocol=request.scheme)

                account_object.save()
            success_url = reverse('leads:list')
            if request.POST.get("savenewform"):
                success_url = reverse("leads:add_lead")
            return JsonResponse({'error': False, 'success_url': success_url})
        print(form.errors)
        return JsonResponse({'error': True, 'errors': form.errors})
    context = {}
    context["lead_form"] = form
    context["accounts"] = Account.objects.filter(status="open")
    context["users"] = users
    context["countries"] = COUNTRIES
    context["status"] = LEAD_STATUS
    context["source"] = LEAD_SOURCE
    context["ctype"] = TYPE
    context["product"] = Products.objects.all()
    context["assignedto_list"] = [int(i) for i in request.POST.getlist('assigned_to', []) if i]

    return render(request, template_name, context)

my views.py

**Comment by admill1519** [comment]
class LeadForm(forms.ModelForm):
    teams_queryset = []
    teams = forms.MultipleChoiceField(choices=teams_queryset)

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        super(LeadForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        if self.data.get('status') == 'converted':
            self.fields['account_name'].required = True
            self.fields['email'].required = True
        self.fields['first_name'].required = False
        self.fields['last_name'].required = False
        self.fields['title'].required = True
        if assigned_users:
            self.fields['assigned_to'].queryset = assigned_users
        self.fields['assigned_to'].required = False

        for key, value in self.fields.items():
            if key == 'phone':
                value.widget.attrs['placeholder'] =\
                    'Enter phone number with country code'
            else:
                value.widget.attrs['placeholder'] = value.label

        self.fields['first_name'].widget.attrs.update({
            'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update({
            'placeholder': 'Last Name'})
        self.fields['account_name'].widget.attrs.update({
            'placeholder': 'Account Name'})
        self.fields['phone'].widget.attrs.update({
            'placeholder': '+91-123-456-7890'})
        self.fields['description'].widget.attrs.update({
            'rows': '6'})
        self.fields['address_line'].widget.attrs.update({
            'placeholder': 'Address Line'})
        self.fields['street'].widget.attrs.update({
            'placeholder': 'Street'})
        self.fields['city'].widget.attrs.update({
            'placeholder': 'City'})
        self.fields['state'].widget.attrs.update({
            'placeholder': 'State'})
        self.fields['postcode'].widget.attrs.update({
            'placeholder': 'Postcode'})

        self.fields["country"].choices = [
            ("", "--Country--"), ] + list(self.fields["country"].choices)[1:]
        self.fields["teams"].choices = [(team.get('id'), team.get('name')) for team in Teams.objects.all().values('id', 'name')]
        self.fields["product"].choices = [pro.get('name') for pro in Products.objects.all().values('name')]
        self.fields["teams"].required = False
        self.fields["ctype"].required = True

    def clean_product(self):
        products = self.cleaned_data.get('products')
        if not Products.objects.filter(name__in=products):
            raise forms.ValidationError('select valid products')
        return products


    class Meta:
        model = Lead
        fields = ('assigned_to', 'first_name',
                  'last_name', 'account_name', 'title',
                  'phone', 'email', 'status', 'source',
                  'website', 'description',
                  'address_line', 'street',
                  'city', 'state', 'postcode', 'country','ctype','product'
                  )

forms.py

**Comment by admill1519** [comment]
I want to achieve exactly the same thing that you did with assigned_to. The user selects the multiple products and in the database, it should save id's of the selected product and same with editing leads

**Comment by admill1519** [comment]
> @admill1519 please use the above updated code, you need to send products info in **product** variable.

how to do it?
