### ISSUE TITLE
Hello vineeshan

### ISSUE THREAD

**Issue by scaphilo** [MicroPyramid/Django-CRM#3]
There is already a quite far developed django based crm.
I would appreciate when we could start to work together on the same project.
Let us discuss by email aaron.riedener@gmail.com

**Comment by vineeshan** [comment]
Hi, it's great to have a talk with you. I've seen "koalixcrm", it's really great work. Our CRM is quite different & massive application. We are still in the developing phase and soon we are going to deploy an application "Microtrack". Which is a combination HR management, Project Management and CRM.

**Comment by scaphilo** [comment]
Sounds interesting ... could we think about aligning the CRM part of your
application?
The goal of the koalixcrm is to provide only the models and making use of
the admin views where ever possible.
So it would be very easy fo you to put something on top of it.

For me it would be very useful to get some feedback and testing from your
side aswell. When i look into your first commits i have the feeling your
know quite well what your planning to do and i could learn a lot form your
inputs.

If we do not align i think it would at least be good to keep in touch.


2017-07-31 9:51 GMT+02:00 vineeshan <notifications@github.com>:

**Comment by ashwin31** [comment]
@scaphilo we aim to develop complete CRM solution and that's in early stages. you will see the progress in coming months.
