### ISSUE TITLE
Change email settings to use full email address.

### ISSUE THREAD

**Issue by AceScottie** [MicroPyramid/Django-CRM#305]
Using PasswprdResetView shoud just use the stored EMAIL_HOST_USER as is for the sender or an alternate setting should be used to determin the from address and the host_user.

line 433 of /common/views.py: from_email = 'no-reply@' + settings.EMAIL_HOST_USER + '.com'
->
from_email = settings.EMAIL_HOST_USER

This will allow common email systems to be used (such as outlook, gmail, yahoo etc.)

**Comment by vineeshan** [comment]
@AceScottie We have changed the settings. You can check it now.
