### ISSUE TITLE
FilterError at /login/

### ISSUE THREAD

**Issue by Sidon** [MicroPyramid/Django-CRM#31]
Unable to apply CachedCompilerFilter (sass --scss {infile} {outfile})
Could not find an option named "scss".

Usage: sass <input> [output]

COMPRESS_PRECOMPILERS = (
    ('text/less', 'lessc {infile} {outfile}'),
    ('text/x-sass', 'sass {infile} {outfile}'),
    ('text/x-scss', 'sass --scss {infile} {outfile}'),
)

I removed the -css on settings and work.
What is wrong?

**Comment by ashwin31** [comment]
@Sidon You need to install sass and less compilers. I will update installation instructions and release by docker to make it much easier.

**Comment by ashwin31** [comment]
@khushish22 Check updated installation instructions.

**Comment by ashwin31** [comment]
@Sidon check updated installation instructions.

**Comment by ashwin31** [comment]
@vermaakarsh https://github.com/MicroPyramid/Django-CRM/blob/master/docs/source/index.rst

**Comment by koushag** [comment]
Hi, I am also having this issue. I have installed sass and less. That above link did not help me at all.
