### ISSUE TITLE
ImportError: cannot import name 'Celery' from 'celery'

### ISSUE THREAD

**Issue by saurabh124** [MicroPyramid/Django-CRM#310]
on running the manage.py migrations its showing error ImportError: cannot import name 'Celery' from 'celery'

**Comment by ashwin31** [comment]
@saurabh124 did you install requirements?

**Comment by saurabh124** [comment]
Yes

**Comment by saurabh124** [comment]
Working fine after reinstalling requirements

**Comment by apacrelocation** [comment]
How did you fix it Arjun, i am getting that error. It was working perfectly, but after few days when i start doing the project again it got this error

**Comment by dalinxz** [comment]
Encountered the same issue, still working on trying to get it working...
