### ISSUE TITLE
FilterError at /login/ when i tried to configure this application in windows locally

### ISSUE THREAD

**Issue by apacrelocation** [MicroPyramid/Django-CRM#320]
Hi Guys, When i tried to configure in windows local host i am getting the following error

![image](https://user-images.githubusercontent.com/42902182/66456825-45037700-eaa1-11e9-8cc4-fd0ad004b21c.png)

**Comment by vineeshan** [comment]
@apacrelocation Please install system requirements https://github.com/MicroPyramid/Django-CRM#system-requirements to get rid of these kind of issues

**Comment by apacrelocation** [comment]
Yup it works now, i have installed Saas
