### ISSUE TITLE
java install failed

### ISSUE THREAD

**Issue by flyonok** [MicroPyramid/Django-CRM#327]
on Ubuntu 16.04.3 LTS run following command failed
`sudo apt-get install oracle-java8-installer -y java -version`

result is:
`apt 1.2.29 (amd64)
Supported modules:
 Ver: Standard .deb
 Pkg:  Debian dpkg interface (Priority 30)
 Pkg:  Debian APT solver interface (Priority -1000)
 S.L: 'deb' Debian binary tree
 S.L: 'deb-src' Debian source tree
 Idx: Debian Source Index
 Idx: Debian Package Index
 Idx: Debian Translation Index
 Idx: Debian dpkg status file
 Idx: Debian deb file
 Idx: Debian dsc file
 Idx: Debian control file
 Idx: EDSP scenario file
E: Command line option 'e' [from -version] is not understood in combination with the other options.`

**Comment by ashwin31** [comment]
@flyonok  is it for elastic search? It's better you run elasticsearch with docker. The current documentation is created for ubuntu 18.04 

try https://hub.docker.com/_/elasticsearch

**Comment by flyonok** [comment]
@ashwin31 ok，thanks.
