### ISSUE TITLE
Demo Credentials are not working

### ISSUE THREAD

**Issue by carlos22** [MicroPyramid/Django-CRM#36]
> Credentials to CRM Dashboard:
> 
>         Email: admin@micropyramid.com
>         Password: admin
Not working on https://django-crm.micropyramid.com/login/?next=/

**Comment by vineeshan** [comment]
@carlos22 Can you try now, with the same login credentials.

**Comment by carlos22** [comment]
Works now, thanks :+1:

**Comment by pashadia** [comment]
I think this should be reopened, since the credentials don't seem to work.

**Comment by vineeshan** [comment]
@pashadia Given credentials are working now

**Comment by mujib-programmer** [comment]
Demo credentials is not working again in demo site.

**Comment by udduu** [comment]
@mujib-programmer Test Credentials are working fine now. Please check it once.

**Comment by mujib-programmer** [comment]
confirmed. test credentials are working now on demo web site.

by the way, I am interested to join in this project. What should I do?

**Comment by khashashin** [comment]
Is there any Demo site? https://demo.django-crm.io/login/?next=/ <--------- not working
