### ISSUE TITLE
Demo link broken

### ISSUE THREAD

**Issue by hanson2010** [MicroPyramid/Django-CRM#375]

**Comment by hanson2010** [comment]
Duplicate of #366

**Comment by MindfulMe** [comment]
Here is the demo for you guys:

https://crm.citvy.com/

Credentials:
email: alice.gogolauri@gmail.com
password: q363602qwE

Feel free to explore user functionality. Admin is not available for you :) Sign in works, no signup though for now. We will add registration for you via https://citvy.com so signup is going to be working in several hours. 🤟
