### ISSUE TITLE
Error creating superuser

### ISSUE THREAD

**Issue by rjschave** [MicroPyramid/Django-CRM#389]
Cloned copy of repo today (commit 4f0e1ae).

It seems the instructions may need to be updated.  Instructions indicate the following:
```
pip install -r requirements.txt
cp crm/local_settings.example crm/local_settings.py
python manage.py makemigrations
python manage.py createsuperuser
python manage.py runserver
```

local_settings.example doesn't exist, but _local_settings.py does. I ran the following command
```
cp crm/_local_settings.py crm/local_settings.py
```

I think ``` python manage.py makemigrations``` should be ``` python manage.py migrate```

After running ```migrate``` command I ran ```createsuperuser``` and received an error.  The stack track is ~ 70 lines, but here are the relevant bits:

psycopg2.errors.NotNullViolation: null value in column "company_id" violates not-null constraint
django.db.utils.IntegrityError: null value in column "company_id" violates not-null constraint

These errors occur when attempting to insert the user record into the table.

From the User model, it's clear the company field is required, but the createsuperuser does not account for this.

From common/models.py:
```
class User(AbstractBaseUser, PermissionsMixin):
   ...
   company = models.ForeignKey(Company, on_delete=models.CASCADE)
```

**Comment by liangsqrt** [comment]
I had the same problem

**Comment by bdbais** [comment]
I had same problem too.
I will try to put a default value top model ,default='Ombrella Corp.'

**Comment by bdbais** [comment]
sudo su - postgres

psql

dj_crm=# \d common_company
                                      Table "public.common_company"
   Column   |          Type           | Collation | Nullable |                  Default
------------+-------------------------+-----------+----------+--------------------------------------------
 id         | integer                 |           | not null | nextval('common_company_id_seq'::regclass)
 name       | character varying(100)  |           |          |
 address    | character varying(2000) |           |          |
 sub_domain | character varying(30)   |           | not null |
 user_limit | integer                 |           | not null |
 country    | character varying(3)    |           |          |


 INSERT INTO common_company (name,sub_domain,user_limit,country) VALUES ('Ombrella Corp','IT',9999,'USA');

dj_crm=# select * from common_company;

 id |     name      | address | sub_domain | user_limit | country
----+---------------+---------+------------+------------+---------
  2 | Ombrella Corp |         | IT         |       9999 | USA
(1 row)

\q

exit

on file:  common/models.py   change default of company with id of your company ( in my test id = 2)

```
class User(AbstractBaseUser, PermissionsMixin):
    file_prepend = "users/profile_pics"
    username = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(("date joined"), auto_now_add=True)
    role = models.CharField(max_length=50, choices=ROLES)
    profile_pic = models.FileField(
        max_length=1000, upload_to=img_url, null=True, blank=True
    )
    has_sales_access = models.BooleanField(default=False)
    has_marketing_access = models.BooleanField(default=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE,default=2)
```

save file and do : 

python manage.py makemigrations
Migrations for 'common':
  common/migrations/0022_auto_20200612_1404.py
    - Alter field company on user

 python manage.py migrate
Operations to perform:
  Apply all migrations: accounts, auth, cases, common, contacts, contenttypes, emails, events, invoices, leads, marketing, opportunity, planner, sessions, tasks, teams, thumbnail
Running migrations:
  Applying common.0022_auto_20200612_1404... OK


python manage.py createsuperuser

Email: dr.oswell@ombrellacorp.com
Username: crm
Password:
Password (again):
Superuser created successfully.

**Comment by bdbais** [comment]
python manage.py runserver 0.0.0.0:9000

http://127.0.0.1:9000/login

I have this error on login:
```
500
The page you're looking for could not be found.
Make sure the address is correct and that the page hasn't moved.

Please contact your administrator if you think this is a mistake.

GO back Home CRM Home
There may be an issue related to System Requirements,

install these packages to resolve them.
```

Home page show:
```
bottlecrm
Coming soon ...
```

probably is not ready to work?

**Comment by bdbais** [comment]
python manage.py collectstatic

```
    raise ImproperlyConfigured("You're using the staticfiles app "
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
```

but on crm/settings.py


```
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STORAGE_TYPE = os.getenv("STORAGE_TYPE", "normal")

if STORAGE_TYPE == "normal":
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    MEDIA_URL = "/media/"

    STATIC_URL = "/static/"
    STATICFILES_DIRS = (BASE_DIR + "/static",)
    COMPRESS_ROOT = BASE_DIR + "/static/"

...

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
)

```

and directory exist:

`drwxrwxr-x  7 crm crm  4096 Jun 12 08:44 static`

**Comment by shaikhmasud147** [comment]
Same issue facing me. @bdbais you getting any solution for this.

**Comment by ashwin31** [comment]
This is going to be SaaS. So, no need of super user.

**Comment by shaikhmasud147** [comment]
@ashwin31  Ok. Please let me know how can i login with subdomain? What is exact process so i can login. Please help me for this. thanks

**Comment by ashwin31** [comment]
Add the subdomain to your host config file. /etc/hosts

**Comment by shaikhmasud147** [comment]
@ashwin31 Company does not exist. Please let me know how can i create company. Please check the screenshot. I have get git repository on my local system. I have also create domain /etc/hosts (django-crm.com).

https://ibb.co/yXNsbcp

I am tring to register new company but get the error. Please check the link
https://ibb.co/nbYNNGH

**Comment by nevros** [comment]
Seems there has been some changes to the code but this issue still remains. The migration does not create the default Company anymore so I was able to add this into the database directly and update the user to be a part of this company.

Point to note is that the Company sub_domain should be 'tenant1.localhost' and the name 'tenant1'

Getting started with this project is not the easiest.

**Comment by ashwin31** [comment]
@rjschave @liangsqrt @bdbais @shaikhmasud147 @nevros check readme.md I made it easy to setup and configure in local machines. Let me know if you find any further difficulties.

**Comment by ashwin31** [comment]
@nevros you don't need to add company or user to database. You can register new company and user from the UI.

**Comment by nevros** [comment]
How does one do that?  I was following the readme and it does not provide much information on how to sign in.

**Comment by ashwin31** [comment]
Ok, Today, I will do a video and add to readme.md
