### ISSUE TITLE
release docker images

### ISSUE THREAD

**Issue by ashwin31** [MicroPyramid/Django-CRM#39]
- [ ]  and add badges to README
- [ ] add docker release info to wiki

**Comment by ashwin31** [comment]
Hi @shadiakiki1986 those are old ones, we are settingup CI/CD and will release it soon. It should be done sometime this week.

**Comment by shadiakiki1986** [comment]
Following up on this, I noticed that you're linking to https://hub.docker.com/r/micropyramid/django-crm/ now. Is this the correct docker image to use?

**Comment by ashwin31** [comment]
yes @shadiakiki1986
