### ISSUE TITLE
demo down

### ISSUE THREAD

**Issue by onno-timmerman** [MicroPyramid/Django-CRM#390]
You demo site is down

**Comment by rjschave** [comment]
Duplicate of #366 & #375?

**Comment by MindfulMe** [comment]
Here is the demo for you guys:

https://crm.citvy.com/

Credentials:
email: alice.gogolauri@gmail.com
password: q363602qwE

Feel free to explore user functionality. Admin is not available for you :) Sign in works, no signup though for now. We will add registration for you via https://citvy.com so signup is going to be working in several hours. 🤟

**Comment by wancheng** [comment]
https://crm.citvy.com/ is down

**Comment by ashwin31** [comment]
it's bottlecrm.com. check readme for more details.

**Comment by ashwin31** [comment]
@wancheng it's https://bottlecrm.com. check readme for more details.
