### ISSUE TITLE
Live Demo available at crm.citvy.com (June 2020) - works

### ISSUE THREAD

**Issue by MindfulMe** [MicroPyramid/Django-CRM#391]
Here is the demo for you guys:

https://crm.citvy.com/

Credentials:
email: alice.gogolauri@gmail.com
password: q363602qwE

Feel free to explore user functionality. Admin is not available for you :) Sign in works, no signup though for now. We will add registration for you via https://citvy.com so signup is going to be working in several hours. 🤟

**Comment by MindfulMe** [comment]
We are working on creating a general signup system for viewing live demo in case someone  alice.gogolauri@gmail.com, please do not change password👳🏿‍♂️

**Comment by MindfulMe** [comment]
Dear friends, to create your own account signup with Facebook on https://citvy.com/signup and then go to https://crm.citvy.com and use your Facebook email (email connected to your Facebook account) and the password: **q363602qwE**

**Comment by Dagorik** [comment]
Thanks!!!

**Comment by weslly99** [comment]
@MindfulMe the link is not working.

**Comment by ashwin31** [comment]
Demo is available at bottlecrm.com
