### ISSUE TITLE
Company does not exist

### ISSUE THREAD

**Issue by shaikhmasud147** [MicroPyramid/Django-CRM#394]
@ashwin31 Company does not exist. Please let me know how can i create new company. Please check the screenshot. I have get git repository on my local system. I have also create domain /etc/hosts (django-crm.com).

https://ibb.co/yXNsbcp

I am tring to register new company but get the error. Please check the link
https://ibb.co/nbYNNGH

Please share the DJANGO-CRM demo link if available.

**Comment by meat-source** [comment]
Все через жопу. Демонстрационные ссылки не работают, ни в документации ни в вопросах. Пол дня убил чтобы запустить. SASS вообще тут зачем? А как все же запустил прилетела та же  ошибка " Компания не существует". Пойду искать что-нибудь другое.

**Comment by alvinahmadov** [comment]
От индусов никакой пользы

**Comment by ashwin31** [comment]
@shaikhmasud147 and @meat-source check readme.md I made it easy to setup and configure in local machines. Let me know if you find any further difficulties.
