### ISSUE TITLE
"The SECRET_KEY setting must not be empty."

### ISSUE THREAD

**Issue by DoctorNasa** [MicroPyramid/Django-CRM#412]
Can not run case "The SECRET_KEY setting must not be empty.

**Comment by rayudu4u** [comment]
You need to set environment variables to run project. For environment variables list please check env.md file

**Comment by nauman-Zeta** [comment]
> You need to set environment variables to run project. For environment variables list please check env.md file
how can i set set environment variables ? for example how can i put the secret key to my settings.py file

**Comment by nauman-Zeta** [comment]
how can i set set environment variables ? for example how can i put the secret key to my settings.py file

**Comment by navidagz** [comment]
@nauman-Zeta create a file name `.env` in the root of the project and put the environment variables there like below:
```
SECRET_KEY="********"
```

**Comment by JayRajdhar** [comment]
SECRET_KEY = os.getenv("SECRET_KEY")  # this will look for a SECRET_KEY in your OS environment variables.

alternative way to to avoid  "The SECRET_KEY setting must not be empty" error you can use a default value for the key.

SECRET_KEY = os.getenv("SECRET_KEY", default = default_key )   # where default_key is a string of length 50.

**Comment by ashwin31** [comment]
Thank you @JayRajdhar, added default secret key.
