### ISSUE TITLE
installation procedure unclear

### ISSUE THREAD

**Issue by akillar** [MicroPyramid/Django-CRM#417]
Hello,
i'm trying to set up the django-crm for a test run, i'm at a loss in implementing celery.
so far what i have done 
1. create virtualenv 
2.  clone django-crm
3. create postgres user+db
4. copied env.md to .env then added the db +other info

i get a error message  when try to run migrate

 from .celery import app as celery_app
  File "/root/crm/django-crm/crm/celery.py", line 3, in <module>
    from celery import Celery
ModuleNotFoundError: No module named 'celery'

any pointers to solve this would be much appreciated.

**Comment by justinmerrell** [comment]
It looks like celery is listed with their requirements.txt did you make sure you had that package installed?

**Comment by akillar** [comment]
i did stalled in fresh vps instance and everything installed smoothly.
