### ISSUE TITLE
ANYONE WHO WANT TO RUN THE CODE 

### ISSUE THREAD

**Issue by sunset1234321** [MicroPyramid/Django-CRM#454]
I spend months on making it works

https://github.com/LoveProgramming-Limited/Django-CRM-2

docker-compose up -- build

**Comment by ashwin31** [comment]
Hi @sunset1234321 I appreciate your work. 

We are moving towards reactjs based frontend and flutter mobile app while keeping this repository to act as API 
https://github.com/MicroPyramid/react-crm
https://github.com/MicroPyramid/flutter-crm

**Comment by sunset1234321** [comment]
@ashwin31     thanks for informing the plan!!!!  Hope the other two repositories will get more exposure gradually.        I love  react and flutter too!

**Comment by ashwin31** [comment]
@sunset1234321 can you add the docker compose to this repo to help others running it.

**Comment by sunset1234321** [comment]
thanks for the invitation,  but it seems the doc of all the commits after tag 0.6.0 is broken,  also the tests.
Hopefully the master branch could fix these 2,  and then a docker compose yaml will be perfect.
