### ISSUE TITLE
Very broken project website raises concerns about project status

### ISSUE THREAD

**Issue by labeldevops** [MicroPyramid/Django-CRM#455]
The project website is broken with empty / placeholder images instead of real images - what raises concerns about the status of this project: is this project dead?

![image](https://user-images.githubusercontent.com/89897153/146173613-8608fa4c-2510-4408-9020-75d87967de65.png)

![image](https://user-images.githubusercontent.com/89897153/146173635-1c8d93ae-d01e-42ad-ab69-693e006720a8.png)

**Comment by ashwin31** [comment]
This is not dead. It's just that we are not having enough free time to spend on opensource. Doing our best.

**Comment by labeldevops** [comment]
Yu should leave this issue open as long it is not fixed - that is the right way to manage problems.
